### ISSUE TITLE
Edit text in the tab title

### ISSUE THREAD

**Issue by jcesguerram** [GnoxNahte/obsidian-tab-panels#1]
Hi! Very nice looking plugin, congratulations!

I have one request and that is to allow html and/or markdown formatting of the tab names. Here's an image of what I tried, but it didn't work. I don't know if I'm doing something wrong.

![image](https://github.com/user-attachments/assets/9dc5427a-dd2e-4d11-8d26-5a0122c831f4)

This is possible to do in the [Tabs plugin](https://github.com/[xhuajin/obsidian-tabs](https://github.com/xhuajin/obsidian-tabs))

**Comment by GnoxNahte** [comment]
Oh, I didn't know that plugin existed! It seems quite good and has more features than mine? I might use it instead of mine for my personal use haha. Somehow I didn't find out about it when searching for similar plugins before developing this.

I'm curious why you would use my plugin instead of the Tabs plugin, though. The only thing I can think of is the styling.

Well anyway, thanks for the suggestion! Added it!

**Comment by jcesguerram** [comment]
The styling is very important! I had been using that one but yours is makin me doubt because it looks better

**Comment by GnoxNahte** [comment]
Thanks! I think I'll still continue using and updating this plugin, as it allows me to maintain control over the code and quickly implement any fixes or new features without relying and waiting on external updates.

That said, I’m unsure whether to add features that overlap with the other plugin, as it feels like stealing? I'm not sure how open the Tabs plugin developer is. However, if someone requests a feature or if the other plugin isn't maintained, I'll try to implement those features.
