### ISSUE TITLE
Bug report - no longer working on Mac

### ISSUE THREAD

**Issue by paulsnedden** [GnoxNahte/obsidian-tab-panels#12]
### What happened?

After a recent update, the Tab Panels plugin no longer works.
[HomeNote.md](https://github.com/user-attachments/files/18219773/HomeNote.md) is a sample note.

Basically, when the note is loaded, all I see is the "code" inside the ```tab-panels ``` wrapper but it does not get converted/displayed as tabs

I also use Obsidian on a Chromebook and my Pixel 8 android phone, using the same version of Tab Panels. These both work fine.

I've confirmed that Source Mode is not enabled.

### Obsidian Version

1.7.7

### Plugin Version

1.1.3

### OS

MacOS

**Comment by GnoxNahte** [comment]
Sorry, this was my mistake. 

In the update from version 1.0.2 to 1.1.0, I changed the default code block keyword from “tab-panels” to “tabs.” I intended this change to apply only to new users to make the keyword simpler, but it seems the update affected everyone.

For now, you can either:
	•	Navigate to Settings -> Tab Panels -> Codeblock keyword and set it back to “tab-panels.”
	•	Use a search-and-replace tool to change all instances of “tab-panels” to “tabs.”

I’ll highlight this issue in the README since it’s the second time it’s come up. Thanks for letting me know!

**Comment by paulsnedden** [comment]
Ahh, I didn't even notice that change had happened. All good, thank you for the response...happy to close this ticket
