### ISSUE TITLE
Outline is not being populated on Obsidian start up

### ISSUE THREAD

**Issue by dsaperov** [GnoxNahte/obsidian-tab-panels#14]
### What happened?

When I open Obsidian and then open a note with tabs, then Outline is being populated fine. But when I close obsidian without previously closing the note and then opening Obsidian then this note is opening with Obsidian itself but Outline is not being populated. It gets populated only after i close the note and open it again.

![gif3](https://github.com/user-attachments/assets/7a0230f0-2769-48be-af81-3716f654d76e)

### Errors

![image](https://github.com/user-attachments/assets/860ed548-a1a9-4c7b-b3f8-4b5dc9873030)

### Obsidian Version

1.6.7

### OS

Windows

**Comment by GnoxNahte** [comment]
Hopefully, it's fixed! Thanks for the report! Sorry, this cache and outline thing is kind of complicated, handling all the cases. Especially since there's no documentation (that I could find) about this too

This time, the cache was updated but the Outline UI wasn't updated. 

Keep the bugs coming! I'll try to make it as bug-free as possible.
