### ISSUE TITLE
Whats the difference between This plugin and the Tabs plugin?

### ISSUE THREAD

**Issue by Paining1** [GnoxNahte/obsidian-tab-panels#4]
Hi,

I hope all is well, I have a more general question if you dont mind.

What is the difference between this plugin and the typical tabs plugin?

https://github.com/xhuajin/obsidian-tabs

**Comment by GnoxNahte** [comment]
Hi, it's ok, I don't mind.

Well before building the plugin, I somehow missed it when I wanted this feature and was searching for similar plugins.

I only saw these 2:
- https://github.com/ptournet/obsidian-html-tabs
- https://github.com/JeminMau/Obsidian-CodeBlock-Tabs
I didn't really like the styles for them and their last updates were over a year ago so I decided to build my own.

I think the main reason I missed it was because I thought Tabs meant the top part of Obsidian, the part where you can switch between notes, similar to browser tabs. You can see a few plugins referring for that feature when you search tabs in the plugin directory. That was my fault... I should've checked it.

Well as for what's different:
- Different styles
- I haven't tested the performance for the Tabs plugin but mine loads quickly. For both startup time and processing the content (almost instant).
- The Tabs plugin has more features like editing the content inside the tabs easily.

And I guess one more reason on why I haven't deleted the plugin after finding his is: I know the code and can control the updates. For my [previous plugin](https://github.com/GnoxNahte/obsidian-auto-embed), I try to solve every issue I come across. If I can't solve it, I'll at least explain why.

I'll **try not to overlap features** with him, so that we don't conflict too much. Like if someone makes a feature request to easily edit the tab content, I'll point them to his plugin. 

Though I like the different layout for the tabs and how he puts the tabs inside the settings so that users can see changes they made. I might also implement those but that will be all the features that will be the same as his.

**Comment by GnoxNahte** [comment]
Thanks! I used Obsidian's styles as a reference, especially the rounded corners on the tabs.

I haven’t used the Tabs plugin extensively, just tested it briefly, but from what I can tell, both plugins seem to display tab content in a similar way. My plugin doesn’t rely on any framework, while Tabs uses [Vue](https://vuejs.org/) if that's what you meant. Both plugins support displaying checklists, but checking a box doesn’t actually save the state. If you reload the note, the checkbox will revert to its original state.

As for outgoing links, I’m working on it (Issue #3). I asked about it in the Discord, and it seems Obsidian doesn’t officially support this functionality. My current approach is a workaround based on [html-tabs](https://github.com/ptournet/obsidian-html-tabs). I’ve got a basic version working, but I’m not sure what issues it might cause. Worst case scenario is breaking all the links in your notes. To mitigate this, I plan to release it as an experimental feature, disabled by default.

**Comment by GnoxNahte** [comment]
@3-ark Hey I added the feature such that outgoing links will show up. For more info, you can see my comment in this issue https://github.com/GnoxNahte/obsidian-tab-panels/issues/3#issuecomment-2524973652 or you can see the [changelog](https://github.com/GnoxNahte/obsidian-tab-panels/blob/main/CHANGELOG.md#111-2024-12-07)

Please test it and let me know if it works!

**Comment by GnoxNahte** [comment]
Hmm, it works for me... can you send some sample markdown or images of how you set it up?
Also, are there any errors in the console? 

Maybe we should move to a [new issue](https://github.com/GnoxNahte/obsidian-tab-panels/issues/new/choose) too? Since this is unrelated to this issue.

Here's what my tests look like:
![image](https://github.com/user-attachments/assets/8909def3-4704-459d-aa4d-f8744844d825)
Left: Live View/Reading mode
Middle: Source mode
Right: Outgoing links sidebar

Then in the Image file:
![image](https://github.com/user-attachments/assets/504e5c4f-31bc-4f22-98d3-155c70a07407)
Left: Image
Right: Backlinks sidebar

**Comment by GnoxNahte** [comment]
Also, by right, you just need to 
- Enable caching then
- Make a single change in the note that the tab panels is in. Can be anything, adding a space, deleting a character, etc.

Then cache should automatically be updated and it should show in backlinks, outgoing links, etc.

Rebuilding the cache can be used, but not really needed. It's used in situations when for some reason, the cache is messed up. Or when you want to build the cache for the whole vault right after enabling the cache without going to every single note you want the cache to be available and making a change.

And about your question about using your previous notes, yup it should be fine. 
If you want to reset the cache to how it was before you enabled caching, you just need to 
- Disable caching
- Reload obsidian
- (Optional) If you are cautious, you might want to load rebuild Obsidian's own cache (Settings -> File and links -> Advanced -> Rebuild)

For the last question, it should work with existing notes and tab panels. Just need to make a single change in the note.

**Comment by GnoxNahte** [comment]
Great that it works now!

Well, I updated the Readme, Changelog and Release notes anyway. Added this:

> [!TIP]
> **Enabling caching for the first time**
> 
> To update the cache on the file, do one of these
> - Edit the file. It can be anything, adding a space, deleting a character, etc. Note that this only updates the cache for the edited file only.
> - Running "Rebuild cache" from the settings. This goes through your whole vault, finds all the data inside the tab panel code blocks and adds it to Obsidian's cache.

For embedding using ![](pic), I think I'll support it in the next update. But since there's a workaround and it isn't a major bug, I think I'll wait for any other bugs then I'll push an update with that fix together.

Thanks for your feedback :) If you find any other issues please continue to report them!

**Comment by GnoxNahte** [comment]
Well then, I'll close this issue. 

For the original question in this issue, I added another feature, caching, that's different from the Tabs plugin.

A short summary for the caching feature:
It enables Obsidian to process data inside the tab panels, just like it does for regular markdown content.

What this means (similar to Obsidian's standard behaviour, but **now works in tab panels**):
- [Backlinks](https://help.obsidian.md/Plugins/Backlinks) and [Outgoing links](https://help.obsidian.md/Plugins/Outgoing+links) works.
- [Renaming linked files](https://help.obsidian.md/Files+and+folders/Manage+notes#Rename+a+note) updates markdown links in tab panels automatically.
- Headings in tab panels appear in the [Outline](https://help.obsidian.md/Plugins/Outline) (Table of Contents).
- [Tags](https://help.obsidian.md/Editing+and+formatting/Tags) within tab panels are searchable and visible in the [Tags view](https://help.obsidian.md/Plugins/Tags+view).
- Plugins like [Dataview](https://github.com/blacksmithgu/obsidian-dataview) can query and use data within tab panels.

For more info, see the [README](../#cache-experimental)

Feel free to reopen this issue or create another issue if you still have questions.
