### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Paining1** [GnoxNahte/obsidian-tab-panels#5]
### What happened?

The footnote isnt working properly, its displaying the first footnote in my note rather than the one I use when I hover over the footnote.

Though it does display it correctly in the footnote section

### Sample Markdown

(I changed the syntax of tab-panels to tabs)

```tabs
--- Tab 1 Content for tab 1 
This is content ^[Second footnote]
--- Tab 2
This is anotehr footnote
hehe ^[Third footnote]
```

### Obsidian Version

1.7.7

### Plugin Version

1.0.2

### OS

Windows

**Comment by Paining1** [comment]
![image](https://github.com/user-attachments/assets/d02ffde9-fd67-468a-934c-e855e91a8fa1)


Here is an example.

When I hover over the footnote its displaying the first footnote in that note. But in the footnote section, its displaying correctly

**Comment by GnoxNahte** [comment]
Hey thanks for the report, I tried it and could replicate it. I'm still solving the backlinks and outgoing links problem from the previous issues. 

I have no idea why this is happening though. I'm just using Obsidian's [render markdown function](https://docs.obsidian.md/Reference/TypeScript+API/MarkdownRenderer/render), there might be some edge cases that I need to handle. I'll try it after I solve the previous issue!

**Comment by GnoxNahte** [comment]
Hey sorry it took so long to fix this. 

For now, it should support **inline footnotes** but note that it doesn't **named footnotes**. I assume you know the different syntaxes for both but in case you don't:

Using the terms from the [Obsidian Docs](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Footnotes), 
- **Inline footnotes**: `[^Inline footnote]`
- **Named footnotes** (needs both footnote and definition): 
	- Footnote: `[^name]`
	- Footnote definition: `[^name]: footnote definition`

Since your sample markdown uses inline footnotes, you should be fine. In case you are curious, I'll write why it doesn't support named footnotes in the next comment so I can reference it in case other people ask.

Note that you need to turn on _caching_ in the settings

**Comment by Paining1** [comment]
Thank you for the fix!

**Comment by GnoxNahte** [comment]
Updated (Version 1.1.2)! Note of this limitation (Copied from README)

### Caching - Footnotes
To use footnotes inside tabs, ensure that both the *footnote reference* (`[^1]`) and the *footnote definition* (`[^1]: definition`) are placed within the same tabs codeblocks. If either the footnote reference or its definition is located outside the tabs codeblock, Obsidian won't register it and will just display it as text instead of a footnote.

> [!NOTE]
> This doesn't apply for [inline footnotes](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#:~:text=You%20can%20also%20inline,not%20in%20Live%20Preview.) (`^[Inline footnote]`) as they combine the footnote reference and definition together.
